// <auto-generated />
using System;
using Library_Mangement_System.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_Mangement_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924090129_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookBorrowRecord", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("BorrowRecordsId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "BorrowRecordsId");

                    b.HasIndex("BorrowRecordsId");

                    b.ToTable("BookBorrowRecord");
                });

            modelBuilder.Entity("BorrowRecordMember", b =>
                {
                    b.Property<int>("BorrowRecordsId")
                        .HasColumnType("int");

                    b.Property<int>("MembersId")
                        .HasColumnType("int");

                    b.HasKey("BorrowRecordsId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("BorrowRecordMember");
                });

            modelBuilder.Entity("Library_Mangement_System.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Abo ali",
                            AvailableCopies = 5,
                            CategoryId = 1,
                            Price = 9.99m,
                            PublicationYear = 1965,
                            Title = "book1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "The Father of Book",
                            AvailableCopies = 3,
                            CategoryId = 2,
                            Price = 7m,
                            PublicationYear = 1937,
                            Title = "The Book"
                        });
                });

            modelBuilder.Entity("Library_Mangement_System.Models.BorrowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BorrowRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorrowDate = new DateTime(2026, 9, 24, 12, 1, 29, 383, DateTimeKind.Local).AddTicks(8268)
                        },
                        new
                        {
                            Id = 2,
                            BorrowDate = new DateTime(2026, 9, 19, 12, 1, 29, 383, DateTimeKind.Local).AddTicks(8324),
                            ReturnDate = new DateTime(2026, 9, 23, 12, 1, 29, 383, DateTimeKind.Local).AddTicks(8328)
                        });
                });

            modelBuilder.Entity("Library_Mangement_System.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Non-Fiction"
                        });
                });

            modelBuilder.Entity("Library_Mangement_System.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed.ali@mail.com",
                            FullName = "Ahmed Ali"
                        });
                });

            modelBuilder.Entity("BookBorrowRecord", b =>
                {
                    b.HasOne("Library_Mangement_System.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_Mangement_System.Models.BorrowRecord", null)
                        .WithMany()
                        .HasForeignKey("BorrowRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BorrowRecordMember", b =>
                {
                    b.HasOne("Library_Mangement_System.Models.BorrowRecord", null)
                        .WithMany()
                        .HasForeignKey("BorrowRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library_Mangement_System.Models.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Library_Mangement_System.Models.Book", b =>
                {
                    b.HasOne("Library_Mangement_System.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Library_Mangement_System.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
